networks:
  laravel:
    driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: php
    volumes:
      - ./laravel/:/var/www/html/arkvel
    working_dir: /var/www/html/arkvel
    networks:
      - laravel
    expose:
      - "9000"
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile  
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./laravel/:/var/www/html/arkvel
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - laravel
    depends_on:
      - php

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mariadb-data:
